## Nexus Variable
nexus_image: "sonatype/nexus3"
nexus_tag: "latest"
nexus_container_name: "nexus"
nexus_port: 
  - "8081:8081"
  - "5000:5000"
nexus_volumes:
  - "/home/hassan/nexus-data:/sonatype-work"


## Sonarqube Variable
sonar_image: "sonarqube"
sonar_tag: "10.7.0-community"
sonar_container_name: "sonarqube"
sonar_port: 
  - "9000:9000"
sonar_volumes:
  - "/home/hassan/sonar-data:/opt/sonarqube/data"
  - "/home/hassan/sonar-extention:/opt/sonarqube/extensions"


## Docker Variable
docker_image: "docker"
docker_tag: "dind"
docker_container_name: "docker"
docker_volumes:
  - "/home/hassan/docker_data:/var/lib/docker"
  - "/home/hassan/docker_certs:/certs"
  - "/home/hassa/docker_certs_client:/certs/client"
  - "/home/hassan/jenkins_data:/var/jenkins_home"


## Jenkins Variable 
jenkins_image: "jenkins"
jenkins_tag: "0.0.1"
jenkins_container_name: "jenkins"
jenkins_port:
  - "8080:8080"
jenkins_environment:
  - "DOCKER_HOST=tcp://{{ docker_container_name }}"
  - "DOCKER_TLS_VERIFY=1"
  - "TZ=Asia/Tehran"
jenkins_volumes:
  - "/home/hassa/docker_certs_client:/var/jenkins_home/.docker"
  - "/home/hassan/jenkins_data:/var/jenkins_home"
