nesus_ip_address: "192.168.1.104:5000"
## Nexus Variable
nexus_image: "sonatype/nexus3"
nexus_tag: "latest"
nexus_container_name: "nexus"
nexus_port: 
  - "8081:8081"
  - "5000:5000"
nexus_volumes:
  - "/home/hassan/nexus-data:/sonatype-work"


## Sonarqube Variable
sonar_image: "sonarqube"
sonar_tag: "10.7.0-community"
sonar_container_name: "sonarqube"
sonar_port: 
  - "9000:9000"
sonar_volumes:
  - "/home/hassan/sonar-data:/opt/sonarqube/data"
  - "/home/hassan/sonar-extention:/opt/sonarqube/extensions"


## Docker Variable
docker_image: "docker"
docker_tag: "dind"
docker_container_name: "docker"
docker_volumes:
  - "/home/hassan/docker_data:/var/lib/docker"
  - "/home/hassan/docker_certs:/certs"
  - "/home/hassan/docker_certs_client:/certs/client"


## Jenkins Variable 
jenkins_image: "jenkins/jenkins"
jenkins_tag: "2.481"
jenkins_container_name: "jenkins"
jenkins_port:
  - "8080:8080"
jenkins_environment: 
   DOCKER_HOST="tcp://docker:2376"
   DOCKER_TLS_VERIFY="1"
jenkins_volumes:
  - "/home/hassan/docker_certs_client:/var/jenkins_home/.docker"
  - "/home/hassan/jenkins_data:/var/jenkins_home:rw"

## Elasticseach Variable
elastic_image: "elasticsearch"
elastic_tag: "7.9.0"
elastic_container_name: "elasticsearch"
elastic_port:
  - "9200:9200"
  - "9300:9300"
elastic_environment: 
   cluster.name="elastic-local"
   bootstrap.memory_lock="true"
   discovery.type="single-node"
   xpack.security.enabled=true
   ELASTIC_PASSWORD="asus1650"
   ES_JAVA_OPTS="-Xms512m -Xmx512m"

elastic_volumes:
  - "/home/hasan/elasticsearch_data:/usr/share/elasticsearch/data"

## Kibana Variable
kibana_image: "kibana"
kibana_tag: "7.9.0"
kibana_container_name: "kibana"
kibana_port:
  - "5601:5601"
kibana_environment: 
  ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
  ELASTICSEARCH_USERNAME="elastic"
  ELASTICSEARCH_PASSWORD="asus1650"

## Filebeat Config
volume_file_path: "filebeat.yaml"
filebeat_config:
  type: container
  path: '/var/lib/docker/containers/*/*.log'
  elastic_url: "http://<ip>"


## Filebeat Variable
filebeat_image: "elastic/filebeat"
filebeat_tag: "7.14.0"
filebeat_container_name: "filebeat"
filebeat_volumes:
  - "/var/lib/docker/containers:/var/lib/docker/containers"
  - "{{ volume_file_path }}:/usr/share/filebeat/filebeat.yml"