### Global Configuration
nesus_ip_address: "192.168.4.196:5000"
GLOBAL_USERSYS: 'user'
GLOBAL_GROUPSYS: 'user'
GLOBAL_VOLUME_PATH: '/home/user'


## Nexus Variable
nexus_image: "sonatype/nexus3"
nexus_tag: "latest"
nexus_container_name: "nexus"
nexus_port: 
  - "8081:8081"
  - "5000:5000"
nexus_volumes:
  - "/home/user/nexus-data:/nexus-data"
nexus_state: "started"


## Sonarqube Variable
sonar_image: "sonarqube"
sonar_tag: "10.7.0-community"
sonar_container_name: "sonarqube"
sonar_port: 
  - "9000:9000"
sonar_volumes:
  - "/home/user/sonar-data:/opt/sonarqube/data"
  - "/home/user/sonar-extention:/opt/sonarqube/extensions"
sonar_state: "started"


## Docker Variable
docker_image: "docker"
docker_tag: "dind"
docker_container_name: "docker"
docker_volumes:
  - "/home/user/docker_data:/var/lib/docker"
  - "/home/user/docker_certs:/certs"
  - "/home/user/docker_certs_client:/certs/client"
docker_state: "absent"


## Jenkins Variable 
jenkins_image: "asusvivobook/jenkins"
jenkins_tag: "0.0.1"
jenkins_container_name: "jenkins"
jenkins_port:
  - "8080:8080"
jenkins_environment: 
   DOCKER_HOST="tcp://docker:2376"
   DOCKER_TLS_VERIFY="1"
jenkins_volumes:
  - "/home/user/docker_certs_client:/var/jenkins_home/.docker"
  - "/home/user/jenkins_data:/var/jenkins_home:rw"
jenkins_state: "absent"

## Elasticseach Variable
elastic_image: "docker.arvancloud.ir/elasticsearch"
elastic_tag: "7.16.3"
elastic_container_name: "elasticsearch"
elastic_port:
  - "9200:9200"
  - "9300:9300"
elastic_environment: 
   cluster.name="elastic-local"
   bootstrap.memory_lock="true"
   discovery.type="single-node"
   xpack.security.enabled=true
   ELASTIC_PASSWORD="asus1650"
   ES_JAVA_OPTS="-Xms512m -Xmx512m"

elastic_volumes:
  - "/home/user/elasticsearch_data:/usr/share/elasticsearch/data"
elastic_state: "started"


## Kibana Variable
kibana_image: "docker.arvancloud.ir/kibana"
kibana_tag: "7.16.3"
kibana_container_name: "kibana"
kibana_port:
  - "5601:5601"
kibana_environment: 
  ELASTICSEARCH_URL="http://192.168.4.198:9200"
  ELASTICSEARCH_USERNAME="elastic"
  ELASTICSEARCH_PASSWORD="asus1650"
  xpack.security.user=elastic
kibana_state: "started"


## Filebeat Config
volume_file_path: "./filebeat.yaml"
filebeat_config:
  type: log
  path: '/var/lib/docker/containers/*/*.log'
  elastic_url: "http://192.168.4.198:9200"
  elastic_username: "elastic"
  elastic_password: "asus1650"


## Filebeat Variable
filebeat_image: "docker.arvancloud.ir/elastic/filebeat"
filebeat_tag: "7.16.3"
filebeat_container_name: "filebeat"
filebeat_volumes:
  - "/var/lib/docker/containers:/var/lib/docker/containers"
  - "{{ volume_file_path }}:/usr/share/filebeat/filebeat.yml"
  - "/var/run/docker.sock:/var/run/docker.sock"
filebeat_cpu: "0.5"
filebeat_memory: "1g"
filebeat_state: "started"


## Logstash Variable
logstash_image: "docker.arvancloud.ir/elastic/logstash"
logstash_tag: "7.16.3"
logstash_container_name: "logstash"
logstash_port:
  - "5044:5044"
  - "5045:5045/udp"
  - "514:514/udp"
logstash_volumes:
  - "./pipelines.yaml:/usr/share/logstash/pipeline/logstash.conf"
logstash_environment:
  LS_JAVA_OPTS: "-Xmx2g -Xms2g"
logstash_cpu: "0.5"
logstash_memory: "1g"
logstash_state: "started"
