---
- name: Ensure Directory Exists
  file:
    path: /opt/{{ filebeat_container_name }}
    state: directory
    mode: '0755'

- name: "Render configuration file from template"
  template:
    src: "filebeat.yaml.j2"
    dest: "/opt/filebeat/{{ filebeat_container_name }}.yaml"
    mode: '0644'

- name: Generate docker-compose.yaml from template
  template:
    src: "docker-compose.yaml.j2"
    dest: "/opt/filebeat/docker-compose.yaml"

- name: Set permissions for Filebeats 
  command: chown -R root /opt/filebeat/{{ filebeat_container_name }}.yaml

    #- name: Set permissions for Docker volume
    # command: chown -R '{{ GLOBAL_USERSYS }}':'{{ GLOBAL_GROUPSYS }}' '{{ item }}'
    #loop: "{{ filebeat_volumes | map('regex_replace', '^(.*):.*$', '\\1') | list }}"


- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/opt/{{ filebeat_container_name }}"
    state: present
