---
- name: "Render configuration file from template"
  template:
    src: "../files/filebeat.yaml.j2"
    dest: "{{ volume_file_path }}"
    mode: '0644'

- name: "pull image"
  docker_image:
    name: "{{ filebeat_image }}"
    tag: "{{ filebeat_tag }}"
    source: pull

- name: "Create {{ filebeat_container_name }} "
  docker_container:
    name: "{{ filebeat_container_name }}"
    image: "{{ filebeat_image }}:{{ filebeat_tag }}"
    detach: yes
<<<<<<< HEAD
    user: root
    volumes: "{{ filebeat_volumes }}"
=======
    volumes: "{{ filebeat_volumes }}"
    user: root
>>>>>>> 3c8c4dff9455bb0de6ff6be479af5ae684bfd066
    command: ["filebeat", "-e", "--path.data=/home/data"]
