---
- name: "pull image"
  docker_image:
    name: "{{ sonar_image }}"
    tag: "{{ sonar_tag }}"
    source: pull

- name: "Create {{ sonar_container_name }} "
  docker_container:
    name: "{{ sonar_container_name }}"
    image: "{{ sonar_image }}:{{ sonar_tag }}"
    detach: yes
    ports:  "{{ sonar_port }}"
    volumes: "{{ sonar_volumes }}"
    restart_policy: "on-failure"
    state: "{{ sonar_state | default(DEFAULT_SONAR_STATE) }}"
    cpus: "{{ sonar_cpu | default(DEFAULT_CPU_LIMIT) }}"
    memory: "{{ sonar_memory | default(DEFAULT_MEMOEY_LIMIT) }}"
