- hosts: localhost
  name: Install Requirments All Node
  become: yes
  roles:
  - role: filebeat
    #- role: elastic
    #- role: kibana

          #  - roke: filebeat
          #  - role: nexus
          #  - role: sonarqube
          #- role: docker
          #- role: jenkins

#- hosts: group1
#  name: Install On Group1
#  become: yes
#  roles: 
#  - role: docker
#  - role: jenkins

#- hosts: group2
#  name: install On Group2
#  become: yes
#  roles:
#  - role: sonarqube
#  - role: nexus
