#- hosts: all
#  name: Install Requirments All Node
#  become: yes
#  roles:
    #- role: requirment
    #  - role: filebeat

- hosts: group3
  name: Install On Group1
  become: yes
  roles: 
  - role: fluent-bit
    #- role: elastic
    # - role: kibana
    #- role: elastic

    #- hosts: group1
    #name: install On Group2
    #become: yes
    #roles:
    #- role: sonarqube
    #- role: nexus
    #- role: defectdojo

    #- hosts: group2
    #name: install On Group3
    #become: yes
    #roles:
    #- role: elastic
    #- role: kibana
    #- role: logstash
