- hosts: localhost
  name: Install Requirments All Node
  become: yes
  roles:
  - role: filebeat
    #- role: kibana
          #  - role: nexus
          #  - role: sonarqube
          #- role: docker
          #- role: jenkins
