- hosts: all
  name: Install Requirments All Node
  become: yes
  tasks:
    - name: ensure some pkgs ate installed.
      apt:
       pkg: 
         - vim
         - net-tools
         - apt-transport-https
         - ca-certificates
         - curl 
       state: present
       update_cache: true

    - name: Get gpg key
      copy:
        src: gpg
        dest: /etc/apt/gpg

    - name: Add Gpg Key
      shell: chmod a+r /etc/apt/gpg
      become: true
      
    - name: Add Repository
      shell: echo " deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable " |  tee /etc/apt/sources.list.d/docker.list > /dev/null
      become: true

    - name: Installing ....
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: true


- hosts: group1
  name: Install On Group1
  become: yes
  tasks:
    - name: ensure ncdu is at the latest version
      apt:
       name: bind9-utils
       state: present

- hosts: group2
  name: install On Group2
  become: yes
  tasks:
    - name: ensure net-tools is at the latest version
      apt:
       name: net-tools
       state: present
