---
- name: "pull image"
  docker_image:
    name: "{{ nexus_image }}"
    tag: "{{ nexus_tag }}"
    source: pull

- name: "Create {{ nexus_container_name }} "
  docker_container:
    name: "{{ nexus_container_name }}"
    image: "{{ nexus_image }}:{{ nexus_tag }}"
    detach: yes
    ports:  "{{ nexus_port }}"
    volumes: "{{ nexus_volumes }}"
    restart_policy: "on-failure"
    state: "{{ nexus_state | default(DEFAULT_NEXUS_STATE) }}"
    cpus: "{{ nesus_cpu | default(DEFAULT_CPU_LIMIT) }}"
    memory: "{{ nesus_memory | default(DEFAULT_MEMOEY_LIMIT) }}"
