---
- name: "pull image"
  docker_image:
    name: "{{ nexus_image }}"
    tag: "{{ nexus_tag }}"
    source: pull

- name: "Create {{ nexus_container_name }} "
  docker_container:
    name: "{{ nexus_container_name }}"
    image: "{{ nexus_image }}:{{ nexus_tag }}"
    detach: yes
    ports:  "{{ nexus_port }}"
    volumes: "{{ nexus_volumes }}"
