- name: Ensure Directory Exists
  file:
    path: /opt/{{ nexus_container_name }}
    state: directory
    mode: '0755'

- name: Generate docker-compose.yaml from template
  template:
    src: "docker-compose.yaml.j2"
    dest: "/opt/nexus/docker-compose.yaml"

- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/opt/{{ nexus_container_name }}"
    state: present

- name: Set permissions for Docker volume
  command: chown -R 200 '{{ item }}'
  loop: "{{ nexus_volumes | map('regex_replace', '^(.*):.*$', '\\1') | list }}"

- name: Down Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/opt/{{ nexus_container_name }}"
    state: absent
  tags:
    - down