---
    - name: ensure some pkgs ate installed.
      apt:
       pkg: 
         - vim
         - net-tools
         - apt-transport-https
         - ca-certificates
         - curl 
       state: present
       update_cache: true

    - name: Get gpg key
      copy:
        src: gpg
        dest: /etc/apt/gpg

    - name: Add Gpg Key
      shell: chmod a+r /etc/apt/gpg
      become: true
      
    - name: Add Repository
      shell: echo " deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable " |  tee /etc/apt/sources.list.d/docker.list > /dev/null
      become: true

    - name: Installing ....
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Add live-restore to daemon.json
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "live-restore": true
          }
        mode: '0644'
      notify: Restart Docker