---
- name: "pull image"
  docker_image:
    name: "{{ jenkins_image }}"
    tag: "{{ jenkins_tag }}"
    source: pull

- name: "Create {{ jenkins_container_name }} "
  docker_container:
    name: "{{ jenkins_container_name }}"
    image: "{{ jenkins_image }}:{{ jenkins_tag }}"
    detach: yes
    ports:  "{{ jenkins_port }}"
    env: "{{ jenkins_environment }}"
    restart_policy: "on-failure"
    state: "{{ jenkins_state | default(DEFAULT_JENKINS_STATE) }}"
    volumes: "{{ jenkins_volumes }}"
    links: "{{ docker_container_name }}"
    cpus: "{{ jenkins_cpu | default(DEFAULT_CPU_LIMIT) }}"
    memory: "{{ jenkins_memory | default(DEFAULT_MEMOEY_LIMIT) }}"
