- name: Download key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
- name: Add Repository
  shell: echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" https://pkg.jenkins.io/debian-stable binary/ |  tee /etc/apt/sources.list.d/jenkins.list > /dev/null 

- name: Install pkg 
  apt:
    update_cache: yes
    name:
      - fontconfig
      - openjdk-17-jre
      - jenkins
