---
- name: "pull image {{ elastic_container_name }} "
  docker_image:
    name: "{{ elastic_image }}"
    tag: "{{ elastic_tag }}"
    source: pull

- name: "Create {{ elastic_container_name }} "
  docker_container:
    name: "{{ elastic_container_name }}"
    image: "{{ elastic_image }}:{{ elastic_tag }}"
    detach: yes
    ports:  "{{ elastic_port }}"
    env: "{{ elastic_environment }}"
    restart_policy: "on-failure"
    state: "{{ elastic_state | default(DEFAULT_ELASTIC_STATE) }}"
    volumes: "{{ elastic_volumes }}"
    cpus: "{{ elastic_cpu | default(DEFAULT_CPU_LIMIT) }}"
    memory: "{{ elastic_memory | default(DEFAULT_MEMOEY_LIMIT) }}"