input {
  beats {
    type => "beats"
    port => 5044
  }
}

filter {
  grok {
    match => { 
      "message" => '%{IPORHOST:host_name} - - \[%{HTTPDATE:access_time}\] "%{WORD:http_method} %{DATA:url} HTTP/%{NUMBER:http_version}" %{NUMBER:response_code} %{NUMBER:body_sent_byte} "-" "%{DATA:referrer}" "-"'
    }
    remove_field => ["message"]
  }
}

output {
  elasticsearch {
    hosts => ["http://192.168.4.198:9200"]
    ssl_certificate_verification => false
    user => "elastic"
    password => "asus1650"
    index => "filebeat-docker-%{+YYYY.MM.dd}"
  }
}
